openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is a documentation of the Contacts App.
tags:
  - name: Contacts
    description: Operations about users and contacts
  - name: Auth
    description: Authorization operations
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-7-d3g7.onrender.com
paths:
  /contacts/{contactId}:
    get:
      $ref: '../swagger/path/contacts/contactsId/get.yaml'
    delete:
      $ref: '../swagger/path/contacts/contactsId/delete.yaml'
    patch:
      $ref: '../swagger/path/contacts/contactsId/patch.yaml'
  /contacts:
    post:
      $ref: '../swagger/path/contacts/post.yaml'
    get:
      $ref: '../swagger/path/contacts/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
